:PROPERTIES:
:ID:       9e38295c-c3b8-477f-87a8-bac8ba43cd29
:END:
#+title: The Art of Losing Bernie Sanders
:PROPERTIES:
:ID:       b8af2f46-9470-498e-9595-894854b931cf
:END:
* Source
Author(s): Ettingermentum
[[mu4e:msgid:20250329223133.3.547880554785331f@mg1.substack.com][Title: The Art of Losing Bernie Sanders]]

* Summary
Although for most politicians, their home state holds little
relevance.  In the case of Bernie Sanders, it is mandatory to
understand the state of Vermont and its peculiarities.  This is
because in the time that Bernie was building his movement, countless
over left-wingers had failed to be accepted in their home states.

Vermont was always different from other states, but rarely in a left
wing way. It was a republican northern state where the dominant
position was a support for abolitionism and a rejection of the
Democratic Party. For an entire century, this trend of republicanism
would remain unchanged, even during each of FDR's elections.

This is mainly due to demographic stagnation, where the state saw
relatively small population increases when compared to the rest of the
country. Its demographic stagnation also lead to ideological
stagnation which meant that they did not follow suit to a rapidly
liberalising country.

In the 1950s, things began to change as the conservative and liberal
factions in the state found themselves increasingly at odds with each
other and state Democrats found themselves more incentivize to win
elections due to a lack of support at a federal level. With all these
factors plus a rightward turn by republicans, the democratic party
managed to secure a credible result in the 1952 gubernatorial election
and 2 years after that almost winning it. In 1958, William H. Meyer,
an anti-war forester, was elected to the U.S House. This shift would
be fully cemented in 1962 when Vermont Democrats won the
governorship. Finally, in 1964, Vermont voted against ultra
conservative Barry Goldwater by 33 points, making it clear that the
Republican stranglehold was finally over.

Although partisan attitudes had shifted, it is unclear that this
represented an actual political change: the Democratic Party was
simply the vessel for the mainstream liberalism that had long been
relevant as a factional force within the GOP.  At the same time, the
state experience very rapid demographic shifts with educated wealthy
professional wanting a more rural lifestyle coming into the
state.  More importantly for the states left-ward shift, however, were
the younger, left wing activists of the New Left who became
disillusioned with their own states.

The founding of the Liberty Union party, anti-war and socialist, was
the first move to change the state's politics.  Since republicans and
democrats in Vermont were very ideologically close, LU members ran
their own candidates since spoiler candidates were a non-issue.  Their
initial results were lacklustre, winning only single digit percentage
of votes in Senate and House elections in 1970. Another problem is
that the candidates they were running were not committed to the party
in the long run, as they were mostly failed Democrats who had failed
to secure nominations within their own party.

Bernard Sanders represented a massive downgrade as he was a complete
nobody with no experience in politics. He was only nominated because
he was one of two people interested in running.  He was a relentless
campaigner who would take any chance he got to speak with the media
and consistently articulate his beliefs on wealth inequality and
ending the Vietnam War.  He got very few votes during his first few
runs for senator and governor, clocking in at single digits.

As the years rolled on, his voter share slowly but consistently
increased, partly due to an influx of New Leftists into the state but
also his resonating with the working poor, which were becoming more
prevalent in Vermont.

As Bernie saw modest gains, the LU was rife with internal squabbles
and losing many dedicated volunteers.  In 1977, Bernie resigned from
the party, registered as an independent an retired from politics.

On its face, this showed that a truly left wing outsider approach had
no possibility of working anywhere in the Sates, as Vermont was
uniquely positioned for a left wing breakthrough and only managed
middling voter percentages before collapsing. The only hope was that
more work would eventually lead to greater gains.
